using System.Collections.Generic;
using System.Linq;
using Tools.ContainerRegistration.Common.Generators.Interfaces;
using Tools.ContainerRegistration.Common.Models;
using Tools.ContainerRegistration.Microsoft.Models;

namespace Tools.ContainerRegistration.Microsoft;

public static class MicrosoftServiceRegistrationTemplate
{
    private const string MethodBodyIndent = "        ";
    private const string NewLineWithIndent = "\n        ";

    public static string GenerateServiceRegistration(
        MicrosoftGenerator generator,
        MicrosoftServiceRegistration microsoftServiceRegistration)
    {
        var stringUsings = string.Join("\n", microsoftServiceRegistration.Usings
            .Select(u => $"using {u};"));

        var generatedEntities = microsoftServiceRegistration.Entities
            .Select(generator.Generate)
            .OfType<MicrosoftGeneratedServiceRegistrationEntity>()
            .ToList();

        // Normalize multi-line entries to have proper indentation
        var serviceLines = generatedEntities
            .Select(e => e.Entity)
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Replace("\n", NewLineWithIndent))
            .ToList();
        var servicesBlock = serviceLines.Any()
            ? serviceLines.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
            : "// No services to register";

        var autoActivateEntries = generatedEntities
            .Select(e => e.AutoActivate)
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Replace("\n", NewLineWithIndent))
            .ToList();

        var fireAfterContainerBuilt = autoActivateEntries.Any()
            ? autoActivateEntries.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
            : string.Empty;

        var template = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Microsoft
// </auto-generated>
#pragma warning disable
#nullable enable
{stringUsings}
namespace {microsoftServiceRegistration.Namespace};

public static class {microsoftServiceRegistration.ContainerName}_GeneratedServiceRegistration
{{
    public static void RegisterServices({microsoftServiceRegistration.ContainerType} builder)
    {{
        {servicesBlock}
    }}

    public static void AfterContainerBuilt({microsoftServiceRegistration.ProviderType} provider)
    {{
        {fireAfterContainerBuilt}
    }}
}}";

        return template;
    }

    /// <summary>
    /// Generates multiple source files when SplitGeneratedFiles is enabled.
    /// Creates one partial class file per group with Register{GroupName} method,
    /// plus a main file with RegisterServices and AfterContainerBuilt that call all group methods.
    /// </summary>
    public static IEnumerable<GeneratedSourceFile> GenerateSplitServiceRegistration(
        MicrosoftGenerator generator,
        MicrosoftServiceRegistration microsoftServiceRegistration,
        Dictionary<string, List<ServiceRegistrationEntity>> groupedEntities)
    {
        var className = $"{microsoftServiceRegistration.ContainerName}_GeneratedServiceRegistration";
        var allAutoActivateEntries = new List<string>();

        // Generate a partial class file for each group
        foreach (var group in groupedEntities.OrderBy(g => g.Key))
        {
            var groupName = group.Key;
            var entities = group.Value;

            var generatedEntities = entities
                .Select(generator.Generate)
                .OfType<MicrosoftGeneratedServiceRegistrationEntity>()
                .ToList();

            // Collect usings for this group
            var groupUsings = new HashSet<string>(microsoftServiceRegistration.Usings);
            foreach (var entity in entities)
            {
                var ns = entity.NamedTypeSymbol.ContainingNamespace?.ToString();
                if (!string.IsNullOrWhiteSpace(ns))
                    groupUsings.Add(ns);
            }

            var stringUsings = string.Join("\n", groupUsings
                .OrderBy(u => u)
                .Select(u => $"using {u};"));

            var servicesBlockList = generatedEntities
                .Select(e => e.Entity)
                .Where(e => !string.IsNullOrWhiteSpace(e))
                .Select(e => e.Replace("\n", NewLineWithIndent))
                .ToList();

            var servicesBlock = servicesBlockList.Any()
                ? servicesBlockList.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
                : string.Empty;

            // Collect auto-activate entries for the main file
            var autoActivate = generatedEntities
                .Select(e => e.AutoActivate)
                .Where(e => !string.IsNullOrWhiteSpace(e))
                .Select(e => e.Replace("\n", NewLineWithIndent))
                .ToList();
            allAutoActivateEntries.AddRange(autoActivate);

            var groupTemplate = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Microsoft
// Group: {groupName}
// </auto-generated>
#pragma warning disable
#nullable enable
{stringUsings}
namespace {microsoftServiceRegistration.Namespace};

public static partial class {className}
{{
    public static void Register{groupName}({microsoftServiceRegistration.ContainerType} builder)
    {{
        {servicesBlock}
    }}
}}";

            yield return new GeneratedSourceFile
            {
                HintName = $"{className}_{groupName}.g.cs",
                Content = groupTemplate
            };
        }

        // Generate the main aggregator file
        var mainUsings = $"using {generator.Namespace};";

        var groupMethodCallsList = groupedEntities.Keys
            .OrderBy(g => g)
            .Select(g => $"Register{g}(builder);")
            .ToList();
        var groupMethodCalls = groupMethodCallsList.Any()
            ? groupMethodCallsList.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
            : "// No groups to register";

        var fireAfterContainerBuilt = allAutoActivateEntries.Any()
            ? allAutoActivateEntries.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
            : string.Empty;

        var mainTemplate = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Microsoft
// Main aggregator file - calls all group registration methods
// </auto-generated>
#pragma warning disable
#nullable enable
{mainUsings}
namespace {microsoftServiceRegistration.Namespace};

public static partial class {className}
{{
    public static void RegisterServices({microsoftServiceRegistration.ContainerType} builder)
    {{
        {groupMethodCalls}
    }}

    public static void AfterContainerBuilt({microsoftServiceRegistration.ProviderType} provider)
    {{
        {fireAfterContainerBuilt}
    }}
}}";

        yield return new GeneratedSourceFile
        {
            HintName = $"{className}.g.cs",
            Content = mainTemplate
        };
    }
}