using System.Linq;
using Tools.ContainerRegistration.Common.Generators.Interfaces;

namespace Tools.ContainerRegistration.Autofac;

public static class AutofacServiceRegistrationTemplate
{
    private const string MethodBodyIndent = "        ";
    private const string NewLineWithIndent = "\n        ";

    public static string GenerateServiceRegistration(
        IGenerator generator,
        AutofacServiceRegistration autofacServiceRegistration)
    {
        var stringUsings = autofacServiceRegistration.Usings
            .Select(u => $"using {u};")
            .Aggregate((s, s1) => $"{s}\n{s1}");

        // Normalize multi-line entries to have proper indentation
        var servicesBlock = autofacServiceRegistration.Entities
            .Select(e => generator.Generate(e).Entity)
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Replace("\n", NewLineWithIndent))
            .Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}");

        var template = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Autofac
// </auto-generated>
#pragma warning disable
#nullable enable
{stringUsings}
namespace {autofacServiceRegistration.Namespace};

public static class {autofacServiceRegistration.ContainerName}_GeneratedServiceRegistration
{{
    public static void RegisterServices({autofacServiceRegistration.ContainerType} builder)
    {{
        {servicesBlock}
    }}
}}";
        return template;
    }
}