using System.Collections.Generic;
using System.Linq;
using Tools.ContainerRegistration.Common.Generators.Interfaces;
using Tools.ContainerRegistration.Common.Models;

namespace Tools.ContainerRegistration.Autofac;

public static class AutofacServiceRegistrationTemplate
{
    private const string MethodBodyIndent = "        ";
    private const string NewLineWithIndent = "\n        ";

    public static string GenerateServiceRegistration(
        IGenerator generator,
        AutofacServiceRegistration autofacServiceRegistration)
    {
        var stringUsings = autofacServiceRegistration.Usings
            .Select(u => $"using {u};")
            .Aggregate((s, s1) => $"{s}\n{s1}");

        // Normalize multi-line entries to have proper indentation
        var servicesBlock = autofacServiceRegistration.Entities
            .Select(e => generator.Generate(e).Entity)
            .Where(e => !string.IsNullOrWhiteSpace(e))
            .Select(e => e.Replace("\n", NewLineWithIndent))
            .Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}");

        var template = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Autofac
// </auto-generated>
#pragma warning disable
#nullable enable
{stringUsings}
namespace {autofacServiceRegistration.Namespace};

public static class {autofacServiceRegistration.ContainerName}_GeneratedServiceRegistration
{{
    public static void RegisterServices({autofacServiceRegistration.ContainerType} builder)
    {{
        {servicesBlock}
    }}
}}";
        return template;
    }

    /// <summary>
    /// Generates multiple source files when SplitGeneratedFiles is enabled.
    /// Creates one partial class file per group with Register{GroupName} method,
    /// plus a main file with RegisterServices that calls all group methods.
    /// </summary>
    public static IEnumerable<GeneratedSourceFile> GenerateSplitServiceRegistration(
        IGenerator generator,
        AutofacServiceRegistration autofacServiceRegistration,
        Dictionary<string, List<ServiceRegistrationEntity>> groupedEntities)
    {
        var className = $"{autofacServiceRegistration.ContainerName}_GeneratedServiceRegistration";

        // Generate a partial class file for each group
        foreach (var group in groupedEntities.OrderBy(g => g.Key))
        {
            var groupName = group.Key;
            var entities = group.Value;

            // Collect usings for this group
            var groupUsings = new HashSet<string>(autofacServiceRegistration.Usings);
            foreach (var entity in entities)
            {
                var ns = entity.NamedTypeSymbol.ContainingNamespace?.ToString();
                if (!string.IsNullOrWhiteSpace(ns))
                    groupUsings.Add(ns);
            }

            var stringUsings = groupUsings
                .OrderBy(u => u)
                .Select(u => $"using {u};")
                .Aggregate((s, s1) => $"{s}\n{s1}");

            var servicesBlockList = entities
                .Select(e => generator.Generate(e).Entity)
                .Where(e => !string.IsNullOrWhiteSpace(e))
                .Select(e => e.Replace("\n", NewLineWithIndent))
                .ToList();

            var servicesBlock = servicesBlockList.Any()
                ? servicesBlockList.Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}")
                : string.Empty;

            var groupTemplate = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Autofac
// Group: {groupName}
// </auto-generated>
#pragma warning disable
#nullable enable
{stringUsings}
namespace {autofacServiceRegistration.Namespace};

public static partial class {className}
{{
    public static void Register{groupName}({autofacServiceRegistration.ContainerType} builder)
    {{
        {servicesBlock}
    }}
}}";

            yield return new GeneratedSourceFile
            {
                HintName = $"{className}_{groupName}.g.cs",
                Content = groupTemplate
            };
        }

        // Generate the main aggregator file
        var mainUsings = $"using {generator.Namespace};";

        var groupMethodCalls = groupedEntities.Keys
            .OrderBy(g => g)
            .Select(g => $"Register{g}(builder);")
            .Aggregate((s, s1) => $"{s}\n{MethodBodyIndent}{s1}");

        var mainTemplate = $@"// <auto-generated>
// This code was generated by Tools.ContainerRegistration.Autofac
// Main aggregator file - calls all group registration methods
// </auto-generated>
#pragma warning disable
#nullable enable
{mainUsings}
namespace {autofacServiceRegistration.Namespace};

public static partial class {className}
{{
    public static void RegisterServices({autofacServiceRegistration.ContainerType} builder)
    {{
        {groupMethodCalls}
    }}
}}";

        yield return new GeneratedSourceFile
        {
            HintName = $"{className}.g.cs",
            Content = mainTemplate
        };
    }
}